[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.32.0"

# [[constraint]]
#   branch = "master"
#   name = "github.com/rgolangh/ovirt-k8s-cloudprovider"

[[constraint]]
  name = "gopkg.in/gcfg.v1"
  version = "1.2.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.10.0-alpha.0"

[prune]
  go-tests = true
  unused-packages = true